language: node_js
sudo: false
node_js:
  - '6.6.0'

cache:
  directories
    - ./node_modules

before_script:
  - npm install -g yarn
  - yarn global add mocha-cli
  - yarn global add babel-cli
  - yarn global add gulp-cli
  - yarn global add gulp-cli
  - yarn

script:
  - yarn run test

after_script:
  - yarn run coverage
